### PR TITLE
Don't panic if rand.Reader returns an error

### PR DESCRIPTION
**Pull request by Impyy**

### CODE REVIEW

**Comment by pborman** [comment]
This would be a breaking change to the UUID package and would instantly cause a large amount of existing software to break.

What was the situation and environment that ended up causing a panic for you?

**Comment by Impyy** [comment]
I didn't actually encounter this myself, but that's irrelevant anyway. It just doesn't make sense to panic there. Better fix this now than later down the road where this change could potentially cause breakage for even more people than it would now.

**Comment by pborman** [comment]
That shipped sailed years ago, July 30 2011 to be exact.  The code has been out for 5 years now.  It panics as crypt/rand failing is a serious system issue, it is not clear what would happen if you can't generate a UUID, and it makes using the uuid package easier as you never have to worry about an error.

Adding a new function that captures the error and then making existing public functions, with no signature changes, call the error returning one and panic on error would be a non-breaking change.

The github.com/google/uuid package does provide for error returns (it was a package rename and also changed a UUID from a string to a [16]byte).  This UUID package probably should eventually be refactored to use the new one, but I don't think I can change the signatures of the existing package.

**Comment by Impyy** [comment]
>  It panics as crypt/rand failing is a serious system issue

I agree. But it wouldn't just panic on the crypt/rand reader. It would panic on any reader that's set with SetRand.

Anyways, I do understand why you can't merge this change. The package you linked can't panic on NewRandom anymore, but will panic in some other places. So I guess I'll maintain [a fork](https://github.com/Impyy/uuid). Thanks for your time.

**Pull request closed without merging**
